language: java
jdk: oraclejdk8
os: linux

notifications:
  email:
    recipients:
        - dimcho.nedev+git@gmail.com

cache:
    directories:
        - $HOME/.gradle

before_install:
    - chmod +x gradlew

script:
    - ./gradlew build


    